# Definition: whiskey_disk::deploy
#
# Description
#   This custom definition is designed to programatically generate a 
#   whiskey_disk configuration file, call the appropriate stage/install
#   commands and execute.
#
# Parameters:
#  $deploy_to - path to which to deploy main application
#  $domain - (array) host or list of hosts on which to deploy (these are ssh connect strings) can also optionally include role information for each host
#  $repository - git repo path for main application
#  $branch - git branch to deploy from main application git repo (default: master)
#  $config_branch - git branch to deploy from configuration git repo (default: master)
#  $config_repository - git repository for configuration files
#  $config_target - configuration repository target path to use
#  $deploy_config_to - where to deploy the configuration repository
#  $yaml_path - location to the YAML config for Whiskey Disk Deployment (default: autogenerated by puppet)
#  $post_deploy_script - path to a shell script to run after deployment
#  $post_setup_script - path to a shell script to run after setup
#  $project - project name (used to compute path in configuration checkout)
#  $role (NOT USED ATM)
#  $staleness_check - (true|false) Enabling staleness checking will cause whiskey_disk to check whether the deployed checkout of the repository is out of date ("stale") with respect to the upstream version in git
#  $ssh_options - hash of variables for specific site SSH options.
#  $rake_env -  hash of environment variables to set when running post_setup and post_deploy rake tasks
#
# Actions:
#  - Creates temporary configuration file
#  - Pre-stages files via wd stage on target $domains
#  - Installs Application via wd deploy on target $domains
#
# Requires:
#  This definition has no requirements.
#
# Sample Usage:
#  whiskey_disk::deploy { 'staging':
#    domain     => [ 'local' ],
#    deploy_to  => '/opt/www/staging',
#    repository => 'https://github.com/flogic/larry.git',
#    branch     => 'staging',
#  }
define whiskey_disk::deploy(
  $deploy_to,
  $domain,
  $repository, 
  $branch             = 'master',
  $config_branch      = 'master',
  $config_repository  = '',
  $config_target      = '',
  $deploy_config_to   = '',
  $yaml_path          = '',
  $post_deploy_script = '',
  $post_setup_script  = '',
  $project            = '',
  $role               = '',
  $staleness_check    = 'false',
  $ssh_options        = { },
  $rake_env           = { 'RAILS_ENV' => 'production' }
) {
  include whiskey_disk

  File { 
    owner => 'root',
    group => 'root',
    mode  => '0644',
  }
  Exec {
    path => '/bin:/sbin:/usr/bin:/usr/sbin:/opt/ruby/bin',
  }

  # Variable Init
  $REAL_staleness_check = $staleness_check ? {
    'true'  => '-c',
    default => '',
  }

  $REAL_yaml_path = $yaml_path ? {
    ''      => "${whiskey_disk::params::wk_tmp_dir}/${name}.yml",
    default => $yaml_path,
  }

  $wd_args = "--to=${name} --path=${REAL_yaml_path} ${REAL_staleness_check}" 

  # Safety Checks
  if $config_repository != '' and 
    ($config_target == '' or $deploy_config_to == '' or $project == '') { 
    fail('Must define $config_target/$deploy_config_to/$project when defining $config_repository') 
  }

  # Logic
  file { "${whiskey_disk::params::wk_tmp_dir}/${name}.yml":
    ensure  => 'file',
    content => template('whiskey_disk/deploy.yml.erb'),
    require => Package[$whiskey_disk::params::wk_gem_packages],
  }
  exec { "whiskey_disk-setup-${name}":
    command => "wd setup ${wd_args}",
    require => File["${whiskey_disk::params::wk_tmp_dir}/${name}.yml"],
    before  => Exec["whiskey_disk-install-${name}"],
  }
  exec { "whiskey_disk-install-${name}":
    command => "wd deploy ${wd_args}",
  }
}
